//
//  Server+Compute.swift
//  feather
//
//  Created by samara on 22.08.2024.
//  Copyright © 2024 Lakr Aream. All Rights Reserved.
//  ORIGINALLY LICENSED UNDER GPL-3.0, MODIFIED FOR USE FOR FEATHER
//

import Foundation
import UIKit.UIGraphicsImageRenderer

extension ServerInstaller {
	/// The URL for one of this server's own routes.
	///
	/// Every one of these used to end in `components.url!`. That value is nil
	/// whenever the host will not parse — and the host is `sni()`, which is the
	/// device's own name as often as it is an address, and can come from a
	/// certificate's common name. A name with a space in it was therefore a crash
	/// on the install screen rather than a fallback.
	///
	/// The server is bound to `0.0.0.0`, so loopback is the same socket: if the
	/// real name will not parse, that is what the install is given.
	private func endpointURL(path: String, secure: Bool) -> URL {
		var comps = URLComponents()

		func build(host: String) -> URL? {
			comps.scheme = secure ? "https" : "http"
			comps.host = host
			comps.path = path
			comps.port = port
			return comps.url
		}

		return build(host: sni())
			?? build(host: "127.0.0.1")
			// Unreachable: a loopback host, a port and a path always parse. Here
			// only so that this function has no force unwrap in it.
			?? URL(fileURLWithPath: path)
	}

	/// Whether this server is serving TLS, which is what the install URLs have to
	/// agree with. See `setupApp`.
	private var isSecure: Bool {
		getServerMethod() != 1 && usesTLS
	}

	var plistEndpoint: URL {
		endpointURL(path: "/\(id).plist", secure: isSecure)
	}

	var payloadEndpoint: URL {
		endpointURL(path: "/\(id).ipa", secure: isSecure)
	}

	var pageEndpoint: URL {
		endpointURL(path: "/install", secure: isSecure)
	}

	/// The manifest is generated by a remote service for the "external" install
	/// method; the metadata is interpolated into a query string, so missing
	/// fields become empty ones rather than the force-unwrap crash they used to
	/// be — a package with no `CFBundleShortVersionString` reached exactly this.
	var externalServerLink: String {
		let baseUrl = "https://api.palera.in/genPlist?bundleid=\(app.identifier ?? "")"
			+ "&name=\(app.name ?? "")"
			+ "&version=\(app.version ?? "")"
			+ "&fetchurl=\(payloadEndpoint.absoluteString)"

		guard
			let escaped = baseUrl.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed),
			let encoded = escaped.addingPercentEncoding(withAllowedCharacters: .alphanumerics)
		else {
			return baseUrl
		}

		return encoded
	}

	var iTunesLink: String {
		_iTunesLink(with: plistEndpoint.absoluteString)
	}

	var iTunesLinkExternal: String {
		_iTunesLink(with: externalServerLink)
	}

	private func _iTunesLink(with url: String) -> String {
		return "itms-services://?action=download-manifest&url=\(url)"
	}

	var displayImageSmallEndpoint: URL {
		endpointURL(path: "/app57x57.png", secure: true)
	}

	var displayImageLargeEndpoint: URL {
		endpointURL(path: "/app512x512.png", secure: true)
	}

	var displayImageSmallData: Data {
		_createIcon(57)
	}

	var displayImageLargeData: Data {
		_createIcon(512)
	}
	
	private func _createIcon(_ r: CGFloat) -> Data {
		let renderer = UIGraphicsImageRenderer(size: .init(width: r, height: r))
		let image = renderer.image { ctx in
			UIColor.tintColor.setFill()
			ctx.fill(.init(x: 0, y: 0, width: r, height: r))
		}
		// A renderer always produces PNG data for a bitmap this simple; the
		// force unwrap here was inside the manifest the install reads, so an
		// empty icon is the safer failure of the two.
		return image.pngData() ?? Data()
	}

	var html: String {
		"""
		<html style="background-color: black;">
		<script type="text/javascript">window.location="\(iTunesLinkExternal)"</script>
		</html>
		"""
	}

	var installManifest: [String: Any] {[
		"items": [[
			"assets": [
				[
					"kind": "software-package",
					"url": payloadEndpoint.absoluteString,
				],
				[
					"kind": "display-image",
					"url": displayImageSmallEndpoint.absoluteString,
				],
				[
					"kind": "full-size-image",
					"url": displayImageLargeEndpoint.absoluteString,
				],
			],
			"metadata": [
				"bundle-identifier": app.identifier,
				"bundle-version": app.version,
				"kind": "software",
				"title": app.name,
			],
		],],
	]}

	var installManifestData: Data {
		(try? PropertyListSerialization.data(
			fromPropertyList: installManifest,
			format: .xml,
			options: .zero
		)) ?? .init()
	}
}
